### your site title here

title: Luca Pantea
description: "MSc Student in Artificial Intelligence &nbsp;
 <img src='https://cdn.freebiesupply.com/logos/large/2x/amsterdam-38-logo-png-transparent.png' alt='University Logo' style='max-width: 20px; height: 20px;'> &nbsp;
 University of Amsterdam"

baseurl: #name of GitHub repository
url: https://lucapantea.github.io #custom url to be used instead of GitHub repository
email: luca.p.pantea@gmail.com 

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: luca_pantea
linkedin: lucapantea
# stackoverflow: "#"
github: lucapantea
# researchgate: "#"
# orcid: "#"
# quora: "#"
# instagram: "#"
# facebook: "#"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank 


# Resume settings
resume_avatar:                  "true"
resume_name:                    "Luca Pantea"
resume_title:                   "MSc Student in Artificial Intelligence"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "luca.p.pantea@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
resume_contact_address:         "Amsterdam, The Netherlands"

resume_header_contact_info:     "Amsterdam, The Netherlands • luca.p.pantea@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Graduate Artificial Intelligence student, passionate about <span style='color: #79ba8d;font-weight:900'>Graph Representational Learning</span> with applications in <b>Geometric Deep Learning</b>, <b>Pandemic Forecasting</b>, <b>Recommender Systems</b>, and <b>Fairness in AI</b>. Eager to contribute to the responsible deployment of AI to tackle challenging real-world problems. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_publications:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/lucapantea"
  resume_twitter_url:           "https://twitter.com/luca_pantea"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/lucapantea/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://lucapantea.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
